spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://10.10.6.60:3306/dsgroup-worker?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&&useSSL=false
          username: dsgroup-worker
          password: dsgroup-worker
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        filters: stat     # 属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有：监控统计用的filter:stat、日志用的filter:log4j、防御sql注入的filter:wall
        defaultAutoCommit: true
        initialSize: 2    # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
        max-active: 10    # 最大连接池数量
        min-idle: 1       # 最小连接池数量
        max-pool-prepared-statement-per-connection-size: -1 # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
        max-wait: 5000    # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
        pool-prepared-statements: false  # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
        test-on-borrow: false # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-on-return: false # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
        test-while-idle: true # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
        validation-query: SELECT 1   # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。



#  mybatis-plus 配置  关闭二级缓存  更多配置   https://mybatis.plus/config/
mybatis-plus:
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      select-strategy: not_empty
      id-type: auto



